### ISSUE TITLE
.NET WS Echo Demo TITLE  has too many word repetitions 

### ISSUE THREAD

**Issue by lloish** [kaazing/dotnet.client.tutorials#18]
Kaazing misspelled and repeated 4 times
Web socket echo demo repeated twice
.Net Framework repeated twice

<img width="393" alt="title" src="https://cloud.githubusercontent.com/assets/19213621/15756703/47b74238-28b7-11e6-99cf-110a7504161e.png">

**Comment by ghost** [comment]
Moved to tickets.
